kind: Service 
apiVersion: v1 
metadata: 
  name: flaskapp-svc 
  namespace: flaskapp-ns 
spec:
  selector:
    app: flaskapp-deploy 
  ports:
    - port: 8000
      targetPort: 5000
      protocol: TCP